# Generated by Django 6.0.4 on 2026-05-14 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_and_more'),
        ('core', '0002_roomallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomConditionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=20)),
                ('walls_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=20)),
                ('flooring_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=20)),
                ('furniture_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=20)),
                ('plumbing_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=20)),
                ('electrical_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=20)),
                ('issues', models.TextField(blank=True, help_text='List of issues found')),
                ('recommendations', models.TextField(blank=True)),
                ('inspected_by', models.CharField(max_length=100)),
                ('inspection_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor', 'room_number']},
        ),
        migrations.AlterModelOptions(
            name='roomallocation',
            options={'ordering': ['-allocated_on']},
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.CharField(blank=True, help_text='Comma-separated list or use checkboxes below', max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='area_sqft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='block',
            field=models.CharField(blank=True, help_text='e.g., A, B, C', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='has_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_attached_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='maintenance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Occupancy'), ('double', 'Double Occupancy'), ('triple', 'Triple Occupancy'), ('quad', 'Quad Occupancy')], default='double', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('closed', 'Closed')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='actual_checkout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='allocated_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='scheduled_checkout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.room'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocation', to='accounts.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_number'], name='core_room_room_nu_432710_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['floor'], name='core_room_floor_db7851_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status'], name='core_room_status_0907f7_idx'),
        ),
        migrations.AddIndex(
            model_name='roomallocation',
            index=models.Index(fields=['room'], name='core_roomal_room_id_bb3bea_idx'),
        ),
        migrations.AddIndex(
            model_name='roomallocation',
            index=models.Index(fields=['is_active'], name='core_roomal_is_acti_c1223c_idx'),
        ),
        migrations.AddField(
            model_name='roomconditionreport',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_reports', to='core.room'),
        ),
    ]
