# Generated by Django 5.0.14 on 2026-07-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active'], name='accounts_cu_is_acti_2885e2_idx'),
        ),
    ]
