# Generated by Django 5.0.14 on 2026-05-20 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_announcement_event_leaveapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pinned announcements appear at the top'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('wardens', 'Wardens Only'), ('admins', 'Admins Only')], default='all', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_model', models.CharField(blank=True, help_text="Model name (e.g., 'complaint', 'fee')", max_length=50)),
                ('related_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='operations__recipie_8d666d_idx'), models.Index(fields=['created_at'], name='operations__created_c47644_idx')],
            },
        ),
    ]
