# Generated by Django 5.0.14 on 2026-07-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_announcement_expiry_date_announcement_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_pinned', '-pinned', '-created_at']},
        ),
    ]
